export enum PushStreamTypes {
    NEW_MESSENGER = 'NEW_MESSENGER',
    UPDATED_STATUS_USER = 'UPDATED_STATUS_USER',
    NEW_USER_CHAT = 'NEW_USER_CHAT',
    TYPE_DELETED_MESSENGER = 'TYPE_DELETED_MESSENGER',
}