export const SUCCESS = 200;
export const CREATED = 201;
export const ERROR_SERVER = 500;

export const SUCCESS_ACCEPTED = 202; //login by token
export const EMPTY_DATA = 204; //empty data
export const SUCCESS_WAITING_CONFIRM = 209;
export const FAILED = 400;
export const UNPROCESSABLE_ENTITY = 422;   // RFC4918
export const HOLIDAY_EXIST = 428;
export const TOKEN_EXPIRED = 401;
export const NOT_FOUND = 404;
export const PASSWORD_NOT_MATCH = 405;
export const PERMISSION_DENIED = 406;
export const PHONE_EXISTS = 426;
export const PHONE_NOT_EXISTS = 701;
export const BUY_PROMOTION = 802
export const EXPIRE_TIME = 804
export const LOGOUT_ACCOUNT = 606;
export const NEW_TOKEN = 443;
export const SERVER_ERROR = 500
